"""DEMO_MODE support: fixed recommendations instead of LLM + Qdrant.

Enabled with DEMO_MODE=1 in the environment. Data comes from
demo_recommendations.json, generated by prepare_demo.py.
"""
import json
import os

DEMO_MODE = os.getenv("DEMO_MODE") == "1"

_RECOS_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "demo_recommendations.json")
_recos = None


def demo_recos():
    global _recos
    if _recos is None:
        with open(_RECOS_PATH) as f:
            _recos = json.load(f)
    return _recos


def demo_gender_key(gender) -> str:
    return "men" if str(gender or "").lower().startswith("m") else "women"
