error_codes = {
    1001: "Invalid email address is provided",
    1002: "Invalid phone number is provided",
    1003: "User with this email already exists",
    1004: "User with this phone number already exists",
    1005: "Requested data not found",
    1006: "Invalid parameters are provided",
    1007: "User not Registered",
    1008: "Invalid Otp Code",
    1009: "Otp expired",
    1010: "Invalid refresh token",
    1011: "Invalid parameters provided",
    1012: "Access token valid but user not found",
    1013: "Not valid parameters",
    1014: "User preferences not found",
    1015: "Body Shape id is not present",
    1016: "Skin Tone id is not present",
    1017: "Hair Color id is not present",
    1018: "Cloth Pattern id is not present",
    1019: "Cloth Color id is not present",
    1020: "Body Part id is not present",
    1021: "Access token expired/bad token provided",
    1022: "No product is present for this id",
    1023: "Product not found",
    1024: "Invalid Sorting parameter",
    1025: "No product for this id is present",
    1026: "This product is already in your favorite list",
    1027: "Product ID is required",
    1028: "Product is not in your favorite list",
    1029: "Age group ID is not present",
    1030: "Height ID is not present",
    1031: "Weight ID is not present",
    1032: "Product in not present in cart",
    1033: "Product is already present in the cart",
    1034: "No product is present in the cart",
    1035: "Error while running the AI model",
    1036: "Invalid garment_type. Possible values are Upper-Body, Lower-Body, Dress",
    1037: "No file found in the request",
    1038: "No file is selected for upload",
    1039: "Invalid file format.",
    1040: "Could not upload the file",
    1041: "User input for tryon not found",
    1042: "Product not found or not available for tryon",
    1043: "No Product Found",
    1044: "User budget id is not present",
    1045: "Failed to download image"
}