"""added bg_remove_url to Products

Revision ID: 2bae160a66f1
Revises: 713077715083
Create Date: 2024-07-08 23:08:54.951322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bae160a66f1'
down_revision = '713077715083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bg_remove_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('bg_remove_url')

    # ### end Alembic commands ###
