"""empty message

Revision ID: 2f361f18a16c
Revises: d8a1c93a61e3
Create Date: 2024-04-25 11:23:53.382510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f361f18a16c'
down_revision = 'd8a1c93a61e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloth_colors', schema=None) as batch_op:
        batch_op.alter_column('combinations',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloth_colors', schema=None) as batch_op:
        batch_op.alter_column('combinations',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)

    # ### end Alembic commands ###
