"""modified_collection_name

Revision ID: 341036b0e49a
Revises: 2bae160a66f1
Create Date: 2024-07-14 23:04:03.159554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341036b0e49a'
down_revision = '2bae160a66f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_name', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_generic', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_name', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('is_generic')

    # ### end Alembic commands ###
