"""empty message

Revision ID: 51acf1cddfe5
Revises: d784dcb240af
Create Date: 2024-05-31 23:47:06.737660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51acf1cddfe5'
down_revision = 'd784dcb240af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_metadata')

    # ### end Alembic commands ###
