"""empty message

Revision ID: 56de4287d1bd
Revises: dc4783436a29
Create Date: 2024-05-05 00:34:05.393051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56de4287d1bd'
down_revision = 'dc4783436a29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_query', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_age_group', schema=None) as batch_op:
        batch_op.alter_column('name_ar',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('height')
        batch_op.drop_column('weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('user_age_group', schema=None) as batch_op:
        batch_op.alter_column('name_ar',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.drop_table('user_searches')
    # ### end Alembic commands ###
