"""empty message

Revision ID: 5fe6a80a95d9
Revises: 260ac8234d30
Create Date: 2024-05-07 15:16:04.584279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe6a80a95d9'
down_revision = '260ac8234d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_brands', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name_ar',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('img_url',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('product_colors', schema=None) as batch_op:
        batch_op.alter_column('color_hex',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name_ar',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_colors', schema=None) as batch_op:
        batch_op.alter_column('name_ar',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('color_hex',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('product_brands', schema=None) as batch_op:
        batch_op.alter_column('img_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('name_ar',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.drop_table('user_cart')
    # ### end Alembic commands ###
