"""empty message

Revision ID: 713077715083
Revises: 213b7154d4f9
Create Date: 2024-07-04 21:07:59.868809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713077715083'
down_revision = '213b7154d4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_ar', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formal', sa.Boolean(), nullable=True))

    with op.batch_alter_table('collection_name', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_budget_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_budget', ['user_budget_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_budget_id')

    with op.batch_alter_table('collection_name', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.drop_column('formal')

    op.drop_table('user_budget')
    # ### end Alembic commands ###
