"""empty message

Revision ID: 79a890551f69
Revises: 5fe6a80a95d9
Create Date: 2024-05-11 14:12:41.117260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79a890551f69'
down_revision = '5fe6a80a95d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_best_for',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_ar', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_uuid', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('good_fit', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('best_for_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('product_uuid_unique', ['product_uuid'])
        batch_op.create_foreign_key('fk_product_best_for_id', 'product_best_for', ['best_for_id'], ['id'])
        batch_op.drop_column('gender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', name='genderenum'), autoincrement=False, nullable=True))
        batch_op.drop_constraint('fk_product_best_for_id', type_='foreignkey')
        batch_op.drop_constraint('product_uuid_unique', type_='unique')
        batch_op.drop_column('best_for_id')
        batch_op.drop_column('good_fit')
        batch_op.drop_column('product_uuid')

    op.drop_table('product_best_for')
    # ### end Alembic commands ###
