"""empty message

Revision ID: 9b39722432ea
Revises: 51acf1cddfe5
Create Date: 2024-06-09 01:56:59.192773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b39722432ea'
down_revision = '51acf1cddfe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_ar', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('topwear_uuid', sa.UUID(), nullable=True),
    sa.Column('bottom_wear_uuid', sa.UUID(), nullable=True),
    sa.Column('foot_wear_uuid', sa.UUID(), nullable=True),
    sa.Column('accessories_uuid', sa.UUID(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['accessories_uuid'], ['products.product_uuid'], ),
    sa.ForeignKeyConstraint(['bottom_wear_uuid'], ['products.product_uuid'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collection_name.id'], ),
    sa.ForeignKeyConstraint(['foot_wear_uuid'], ['products.product_uuid'], ),
    sa.ForeignKeyConstraint(['topwear_uuid'], ['products.product_uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_items')
    op.drop_table('collection_name')
    # ### end Alembic commands ###
