"""empty message

Revision ID: d51ed11b09c5
Revises: 79a890551f69
Create Date: 2024-05-11 15:53:10.865960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51ed11b09c5'
down_revision = '79a890551f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('product_uuid_unique', type_='unique')
        batch_op.create_index(batch_op.f('ix_products_product_uuid'), ['product_uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_product_uuid'))
        batch_op.create_unique_constraint('product_uuid_unique', ['product_uuid'])

    # ### end Alembic commands ###
