"""empty message

Revision ID: dc4783436a29
Revises: fe7e21db9aa8
Create Date: 2024-05-02 17:16:42.766670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc4783436a29'
down_revision = 'fe7e21db9aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_ar', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_ar', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color_hex', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_ar', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_age_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_ar', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_height',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_ar', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_weight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_ar', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_ar', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], 'sub_category_category_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('name_ar', sa.String(), nullable=True),
    sa.Column('description_ar', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('sizes', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('colors', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('image_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('gender', postgresql.ENUM(name='genderenum',create_type=None), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.Column('tryon_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['product_brands.id'], 'products_brand_id_fkey'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], 'products_category_id_fkey'),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_category.id'], 'products_sub_category_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], 'favorite_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], 'favorite_user_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_group_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('height_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight_id', sa.Integer(), nullable=True))
        batch_op.drop_column('age_group')
        batch_op.create_foreign_key('users_weight_id_fkey', 'user_weight', ['weight_id'], ['id'])
        batch_op.create_foreign_key('users_age_group_id_fkey', 'user_age_group', ['age_group_id'], ['id'])
        batch_op.create_foreign_key('users_height_id_fkey', 'user_height', ['height_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_weight_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('users_age_group_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('users_height_id_fkey', type_='foreignkey')
        batch_op.drop_column('weight_id')
        batch_op.drop_column('height_id')
        batch_op.drop_column('age_group_id')
        batch_op.add_column(sa.Column('age_group', postgresql.ENUM(name='agegroupenum', create_type=False), nullable=True))

    op.drop_table('favorite')
    op.drop_table('products')
    op.drop_table('sub_category')
    op.drop_table('user_weight')
    op.drop_table('user_height')
    op.drop_table('user_age_group')
    op.drop_table('product_sizes')
    op.drop_table('product_colors')
    op.drop_table('product_brands')
    op.drop_table('category')
    # ### end Alembic commands ###
