"""empty message

Revision ID: fe7e21db9aa8
Revises: 2f361f18a16c
Create Date: 2024-04-24 02:28:18.318370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7e21db9aa8'
down_revision = '2f361f18a16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hair_color_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'hair_colors', ['hair_color_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hair_color_id')

    # ### end Alembic commands ###
